import { describe, it, expect } from 'vitest';
import { GROUND_TRUTH_CORPUS } from '../benchmark/groundTruthCorpus';
import { PasswordDetector } from '../privacy/detectors/passwordDetector';
import { EmailDetector } from '../privacy/detectors/emailDetector';
import { PhoneDetector } from '../privacy/detectors/phoneDetector';
import { IdDetector } from '../privacy/detectors/idDetector';
import { ApiKeyDetector } from '../privacy/detectors/apiKeyDetector';
import { CreditCardDetector } from '../privacy/detectors/creditCardDetector';
import { SecretDetector } from '../privacy/detectors/secretDetector';

describe('Benchmark Ground Truth Structural Independence Audit', () => {
  it('proves ground truth is statically and independently declared without detector calls', () => {
    expect(GROUND_TRUTH_CORPUS.length).toBeGreaterThanOrEqual(30);

    for (const testCase of GROUND_TRUTH_CORPUS) {
      // 1. Independent expected bounding box must exist with valid coordinates
      expect(testCase.expectedBBox).toBeDefined();
      expect(testCase.expectedBBox.x).toBeGreaterThanOrEqual(0);
      expect(testCase.expectedBBox.y).toBeGreaterThanOrEqual(0);
      expect(testCase.expectedBBox.width).toBeGreaterThan(0);
      expect(testCase.expectedBBox.height).toBeGreaterThan(0);

      // 2. Expected sensitive flag must be boolean
      expect(typeof testCase.isSensitive).toBe('boolean');

      // 3. Must be completely independent of detector instance state
      expect((testCase as any).detector).toBeUndefined();
    }
  });

  it('fails if benchmark ground truth were derived from detector output (adversarial detector mutation)', () => {
    // If ground truth were dynamically generated by calling detector.detect(),
    // mutating or replacing detector outputs would mutate ground truth.
    // We prove that ground truth is strictly immutable against any detector output manipulation.

    const sampleCase = GROUND_TRUTH_CORPUS[0];
    const initialExpectedBBox = { ...sampleCase.expectedBBox };

    // Malicious/mock detector returning bogus coordinates
    class MaliciousBypassDetector {
      detect() {
        return [
          {
            id: sampleCase.element.id,
            type: 'password' as const,
            bbox: { x: 9999, y: 9999, width: 9999, height: 9999 },
            confidence: 0.01,
            source: 'dom' as const,
            redaction: 'blackout' as const,
          },
        ];
      }
    }

    const mockDetector = new MaliciousBypassDetector();
    const mockOutput = mockDetector.detect();

    // The detector's output MUST NOT alter or equal the independent ground truth
    expect(sampleCase.expectedBBox).toEqual(initialExpectedBBox);
    expect(sampleCase.expectedBBox).not.toEqual(mockOutput[0].bbox);
  });

  it('confirms ground truth source file contains zero imports or calls to detector classes', async () => {
    // Structural source code check: groundTruthCorpus.ts must NOT import any detector
    const fs = await import('fs');
    const path = await import('path');
    const corpusPath = path.resolve(__dirname, '../benchmark/groundTruthCorpus.ts');
    const content = fs.readFileSync(corpusPath, 'utf-8');

    expect(content).not.toContain('PasswordDetector');
    expect(content).not.toContain('EmailDetector');
    expect(content).not.toContain('PhoneDetector');
    expect(content).not.toContain('IdDetector');
    expect(content).not.toContain('ApiKeyDetector');
    expect(content).not.toContain('CreditCardDetector');
    expect(content).not.toContain('SecretDetector');
    expect(content).not.toContain('detector.detect');
  });
});
